# Generated by Django 3.0.4 on 2020-05-15 20:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('denton', django.db.models.manager.Manager()),
            ],
        ),
    ]
